spring.application.name=skillsphere
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsphere_db
spring.datasource.username=postgres
spring.datasource.password=Revathi@3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
